"""
Can this study's design actually recover all five weights?

Run this BEFORE collecting data. It answers the question empirically instead of
by assertion, in two stages:

  1. DESIGN DIAGNOSTICS on the feature matrix participants will really see -
     correlation, variance inflation factors, and the condition number. These
     say whether two weights are mathematically distinguishable at all.

  2. PARAMETER RECOVERY - invent a known weight vector, simulate participants
     choosing by it, fit the model back, and check whether the estimates land on
     the truth. If a weight cannot be recovered from perfect synthetic data
     generated by the model itself, no number of real participants will help:
     the fault is in the design, not the sample size.

Usage
    .venv/Scripts/python.exe studies/weight-elicitation/analysis/check_identifiability.py
    ... --participants 30 50 100 200 --reps 40
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
from scipy.optimize import minimize

HERE = Path(__file__).resolve().parent
STUDY = HERE.parent
DIMS = ["spatial", "accessibility", "facility", "economic", "disruption"]

# A deliberately uneven truth: if the design works, the fit must reproduce the
# ordering as well as the magnitudes.
W_TRUE = np.array([0.30, 0.20, 0.25, 0.15, 0.10])


def load_design(material_path: Path) -> Tuple[List[np.ndarray], List[str]]:
    """One (n_candidates x 5) feature matrix per non-attention task."""
    m = json.loads(material_path.read_text(encoding="utf-8"))
    hotels = m["hotels"]
    anchored = m["anchor_components"]

    designs, labels = [], []
    for task in m["tasks"]:
        if task.get("is_attention_check"):
            continue
        ac = anchored[task["anchor_id"]]
        rows = []
        for hid in task["option_ids"]:
            g = hotels[hid]["components_global"]
            a = ac[hid]
            rows.append([a["spatial"], a["accessibility"],
                         g["facility"], g["economic"], g["disruption"]])
        designs.append(np.asarray(rows, dtype=float))
        labels.append(f'{task["id"]} @ {task["anchor_id"]}')
    return designs, labels


# --------------------------------------------------------------------------- #
# Stage 1 - design diagnostics
# --------------------------------------------------------------------------- #
def diagnostics(X: np.ndarray) -> Dict[str, object]:
    corr = np.corrcoef(X, rowvar=False)

    # VIF_j = 1 / (1 - R^2 of regressing column j on all the others).
    vif = []
    for j in range(X.shape[1]):
        y = X[:, j]
        others = np.delete(X, j, axis=1)
        A = np.column_stack([np.ones(len(others)), others])
        beta, *_ = np.linalg.lstsq(A, y, rcond=None)
        resid = y - A @ beta
        ss_tot = ((y - y.mean()) ** 2).sum()
        r2 = 1 - (resid ** 2).sum() / ss_tot if ss_tot > 0 else 0.0
        vif.append(np.inf if r2 >= 1 else 1.0 / (1.0 - r2))

    Xc = (X - X.mean(0)) / (X.std(0) + 1e-12)
    cond = float(np.linalg.cond(Xc))
    return {"corr": corr, "vif": np.asarray(vif), "cond": cond}


# --------------------------------------------------------------------------- #
# Stage 2 - parameter recovery
# --------------------------------------------------------------------------- #
def simulate_choices(designs: List[np.ndarray], w: np.ndarray,
                     n_participants: int, rng: np.random.Generator,
                     scale: float) -> List[Tuple[np.ndarray, int]]:
    """Each participant does every task; choices follow the logit the model assumes."""
    obs = []
    for _ in range(n_participants):
        for X in designs:
            u = scale * (X @ w)
            p = np.exp(u - u.max())
            p /= p.sum()
            obs.append((X, int(rng.choice(len(X), p=p))))
    return obs


def neg_loglik(theta: np.ndarray, obs: List[Tuple[np.ndarray, int]]) -> float:
    total = 0.0
    for X, k in obs:
        u = X @ theta
        total -= u[k] - (u.max() + np.log(np.exp(u - u.max()).sum()))
    return total


def fit(obs: List[Tuple[np.ndarray, int]], k: int) -> np.ndarray | None:
    res = minimize(neg_loglik, np.zeros(k), args=(obs,), method="BFGS")
    return res.x if res.success or res.status == 2 else None


def normalise(v: np.ndarray) -> np.ndarray:
    """Only the DIRECTION of the weight vector is identified in a logit - the
    overall magnitude trades off against the noise scale. Compare on the simplex,
    which is also how the retriever uses the weights."""
    v = np.clip(v, 0, None)
    s = v.sum()
    return v / s if s > 0 else np.full_like(v, 1 / len(v))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--material", type=Path,
                    default=STUDY / "material" / "study_material_v1.json")
    ap.add_argument("--participants", type=int, nargs="+", default=[30, 50, 100, 200])
    ap.add_argument("--reps", type=int, default=40)
    ap.add_argument("--scale", type=float, default=6.0,
                    help="choice determinism; higher = less random participants")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    designs, labels = load_design(args.material)
    X = np.vstack(designs)

    print(f"Design: {len(designs)} tasks x {designs[0].shape[0]} candidates "
          f"= {X.shape[0]} presented alternatives\n")

    d = diagnostics(X)
    print("1. DESIGN DIAGNOSTICS")
    print("   correlation")
    print("                  " + "".join(f"{x[:9]:>11}" for x in DIMS))
    for i, name in enumerate(DIMS):
        print(f"   {name:<14}" + "".join(f"{d['corr'][i][j]:>11.2f}"
                                         for j in range(len(DIMS))))
    print("\n   variance inflation factor  (>5 shaky, >10 not identifiable)")
    for name, v in zip(DIMS, d["vif"]):
        flag = "  <-- PROBLEM" if v > 10 else ("  <-- shaky" if v > 5 else "")
        print(f"   {name:<16}{v:8.2f}{flag}")
    print(f"\n   condition number: {d['cond']:.1f}"
          f"  ({'ok' if d['cond'] < 30 else 'high - unstable estimates'})")

    print("\n2. PARAMETER RECOVERY")
    print(f"   truth w = {np.round(normalise(W_TRUE), 3).tolist()}")
    print(f"   {args.reps} simulated studies per sample size\n")
    print(f"   {'N':>5}  " + "".join(f"{x[:9]:>12}" for x in DIMS) + f"{'max err':>10}")

    truth = normalise(W_TRUE)
    for n in args.participants:
        rng = np.random.default_rng(args.seed)
        ests = []
        for _ in range(args.reps):
            obs = simulate_choices(designs, W_TRUE, n, rng, args.scale)
            theta = fit(obs, X.shape[1])
            if theta is not None:
                ests.append(normalise(theta))
        if not ests:
            print(f"   {n:>5}   fit failed")
            continue
        E = np.vstack(ests)
        mean, sd = E.mean(0), E.std(0)
        err = np.abs(mean - truth).max()
        cells = "".join(f"{mean[i]:>7.3f}±{sd[i]:.3f}" for i in range(len(DIMS)))
        print(f"   {n:>5}  {cells}{err:>10.3f}")

    print("\n   ± is the spread across repeated simulated studies: it is the "
          "\n   uncertainty you should expect on each weight at that sample size.")


if __name__ == "__main__":
    main()
